# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://ysbchonglab.github.com'
baseurl: ''
title: 'Immuno-Informatics Lab'
description: 'Homepage of IMIL'
permalink: pretty
logo: "/assets/images/Myproject-1.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Research
  url: /research/
- title: Professor
  url: /professor/
- title: Members
  url: /members/
- title: Archive
  url: /blog/
# Footer nav
navigation_footer:
- title: Back to home
  url: "#top"

# Collections
collections:
  posts:
    title: 
    output: true
    description: ""
    feature_text: |
      IMIL Archive
    feature_image: "https://picsum.photos/2560/600?image=866"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
